### PR TITLE
add AERA 2019 presentation abstract in new sharing-out directory

### PR DESCRIPTION
**Pull request by jrosen48**

### CODE REVIEW

**Comment by jrosen48** [comment]
@JesseMostipak and @restrellado here's where we can add the proposal - no emails included, but institutional affiliations are - LMK if this is alright.

**Comment by JesseMostipak** [comment]
works for me!

**Comment by restrellado** [comment]
Works for me too. Thanks!

**Comment by jrosen48** [comment]
Thanks all! Fingers crossed.

**Pull request merged**
